version: "3.9"
services:
  some-mongo:
    image: mongo
    container_name: some-mongo
    ports:
      - 27017:27017
    volumes:
      - 'mongodrive:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
volumes:
  mongodrive:
    external: true